/* ML Quest — configuration: runtime URLs, XP economy, levels, badges, decks */
'use strict';

// Content files push into this global (must exist before data/*.js load)
window.CourseData = { weeks: [], cards: [], dojoExtras: [] };

window.CFG = {
  pyodideVersion: '0.26.4',
  get pyodideIndexURL() { return 'https://cdn.jsdelivr.net/pyodide/v' + this.pyodideVersion + '/full/'; },

  storageKey: 'mlquest_v1',

  xp: {
    lesson: 15,
    quizPerCorrect: 5,
    card: 2,
    bossPass: 150,
    questBonus: 30,
    solutionSeenFactor: 0.5,
  },

  runTimeoutMs: 20000,
  submitTimeoutMs: 45000,

  levels: [
    { xp: 0,    title: 'print("hello")' },
    { xp: 120,  title: 'Loop Literate' },
    { xp: 300,  title: 'Comprehension Comprehender' },
    { xp: 550,  title: 'Pythonista' },
    { xp: 900,  title: 'Data Wrangler' },
    { xp: 1350, title: 'Gradient Descender' },
    { xp: 1900, title: 'Metric Maximalist' },
    { xp: 2600, title: 'Attention Head' },
    { xp: 3400, title: 'Transformer Whisperer' },
    { xp: 4300, title: 'Prompt Engineer' },
    { xp: 5300, title: 'RAG Architect' },
    { xp: 6400, title: 'Agent Overlord' },
    { xp: 7600, title: 'Interview Slayer' },
    { xp: 9000, title: 'Systems Sage' },
    { xp: 10600, title: 'Chief Architect' },
    { xp: 12400, title: 'Fleet Commander' },
    { xp: 14400, title: 'Agent Master' },
  ],

  decks: {
    'python':     { emoji: '🐍', title: 'Python' },
    'classic-ml': { emoji: '📊', title: 'Classic ML' },
    'nlp':        { emoji: '🔤', title: 'NLP & Transformers' },
    'llm':        { emoji: '🧠', title: 'LLMs' },
    'rag':        { emoji: '📚', title: 'RAG' },
    'agents':     { emoji: '🦾', title: 'Agents' },
    'opt':        { emoji: '🎛️', title: 'Training & PEFT' },
    'inf':        { emoji: '🚀', title: 'Inference & Serving' },
    'qtz':        { emoji: '🗜️', title: 'Quantization' },
    'prd':        { emoji: '🛡️', title: 'Production ML' },
    'design':     { emoji: '🏛️', title: 'System Design' },
    'dev-agents': { emoji: '🛠️', title: 'Dev Agents' },
    'biz-agents': { emoji: '💼', title: 'Business Agents' },
  },

  blockMeta: {
    lesson:   { emoji: '📖', label: 'Read' },
    quiz:     { emoji: '❓', label: 'Quiz' },
    exercise: { emoji: '⚔️', label: 'Code' },
    homework: { emoji: '🏗️', label: 'Homework' },
    cards:    { emoji: '🃏', label: 'Flashcards' },
    boss:     { emoji: '👑', label: 'Boss Exam' },
    case:     { emoji: '🏛️', label: 'Design Case' },
  },

  // Badge predicates receive (S, ctx, IDX): state, event context, content index.
  badges: [
    { id: 'first-steps', emoji: '🐣', title: 'First Steps', desc: 'Complete your first activity',
      check: (S) => Object.keys(S.done).length >= 1 },
    { id: 'first-blood', emoji: '⚔️', title: 'First Blood', desc: 'Pass your first coding exercise',
      check: (S, ctx) => ctx.event === 'exercise-pass' },
    { id: 'bug-slayer', emoji: '🐛', title: 'Bug Slayer', desc: 'Pass an exercise after 3+ failed submits',
      check: (S, ctx) => ctx.event === 'exercise-pass' && (S.fails[ctx.id] || 0) >= 3 },
    { id: 'streak-3', emoji: '🔥', title: 'On Fire', desc: '3-day streak', check: (S) => S.streak.count >= 3 },
    { id: 'streak-7', emoji: '⚡', title: 'Unstoppable', desc: '7-day streak', check: (S) => S.streak.count >= 7 },
    { id: 'streak-14', emoji: '🌋', title: 'Volcanic', desc: '14-day streak', check: (S) => S.streak.count >= 14 },
    { id: 'comeback', emoji: '💪', title: 'Comeback Kid', desc: 'Return after a 3+ day break (no shame, just reps)',
      check: (S, ctx) => ctx.comeback === true },
    { id: 'week-1', emoji: '🐍', title: 'Week 1 Cleared', desc: 'Finish all core blocks of Week 1',
      check: (S, ctx, IDX) => IDX.weekDone('w1') },
    { id: 'week-2', emoji: '📊', title: 'Week 2 Cleared', desc: 'Finish all core blocks of Week 2',
      check: (S, ctx, IDX) => IDX.weekDone('w2') },
    { id: 'week-3', emoji: '🤖', title: 'Week 3 Cleared', desc: 'Finish all core blocks of Week 3',
      check: (S, ctx, IDX) => IDX.weekDone('w3') },
    { id: 'week-4', emoji: '🧠', title: 'Week 4 Cleared', desc: 'Finish all core blocks of Week 4',
      check: (S, ctx, IDX) => IDX.weekDone('w4') },
    { id: 'week-5', emoji: '⚙️', title: 'Week 5 Cleared', desc: 'Finish all core blocks of Week 5',
      check: (S, ctx, IDX) => IDX.weekDone('w5') },
    { id: 'week-6', emoji: '🏛️', title: 'Week 6 Cleared', desc: 'Finish all core blocks of Week 6',
      check: (S, ctx, IDX) => IDX.weekDone('w6') },
    { id: 'week-7', emoji: '📐', title: 'Week 7 Cleared', desc: 'Finish all core blocks of Week 7',
      check: (S, ctx, IDX) => IDX.weekDone('w7') },
    { id: 'week-8', emoji: '🛠️', title: 'Week 8 Cleared', desc: 'Finish all core blocks of Week 8',
      check: (S, ctx, IDX) => IDX.weekDone('w8') },
    { id: 'week-9', emoji: '💼', title: 'Week 9 Cleared', desc: 'Finish all core blocks of Week 9',
      check: (S, ctx, IDX) => IDX.weekDone('w9') },
    { id: 'agent-master', emoji: '🤖', title: 'Agent Master', desc: 'Defeat T9 — the final agent gauntlet',
      check: (S, ctx) => ctx.event === 'boss-pass' && ctx.id === 'w9-boss' },
    { id: 'whiteboard', emoji: '🗣️', title: 'Whiteboard Warrior', desc: 'Complete your first design case',
      check: (S, ctx) => ctx.event === 'case-done' },
    { id: 'architect', emoji: '🕶️', title: 'The Architect', desc: 'Defeat T7 — The Architect\'s Gauntlet',
      check: (S, ctx) => ctx.event === 'boss-pass' && ctx.id === 'w7-boss' },
    { id: 'boss-first', emoji: '👑', title: 'Boss Down', desc: 'Pass your first boss exam',
      check: (S, ctx) => ctx.event === 'boss-pass' },
    { id: 'flawless', emoji: '💯', title: 'Flawless', desc: 'Pass a boss with a perfect score',
      check: (S, ctx) => ctx.event === 'boss-pass' && ctx.scorePct === 100 },
    { id: 'offer-ready', emoji: '🏆', title: 'Offer Ready', desc: 'Defeat the final boss — The Interview Gauntlet',
      check: (S, ctx) => ctx.event === 'boss-pass' && ctx.id === 'w5-boss' },
    { id: 'hw-hero', emoji: '🏗️', title: 'Homework Hero', desc: 'Complete every homework in the course',
      check: (S, ctx, IDX) => IDX.allHomeworkDone() },
    { id: 'cards-100', emoji: '🃏', title: 'Century of Cards', desc: 'Review 100 flashcards',
      check: (S) => S.cardsReviewed >= 100 },
    { id: 'quest-5', emoji: '🎯', title: 'Quest Machine', desc: 'Claim 5 daily quests',
      check: (S) => S.questsClaimed >= 5 },
    { id: 'grinder', emoji: '💎', title: 'Grinder', desc: 'Earn 1000 XP', check: (S) => S.xp >= 1000 },
  ],
};
